const API_BASE = import.meta.env.VITE_API_URL || '';

interface AIResponse {
  success: boolean;
  data?: string;
  error?: string;
}

async function callAI(endpoint: string, payload: Record<string, unknown>): Promise<AIResponse> {
  if (!API_BASE) {
    // Return stub response when API not configured
    return getStubResponse(endpoint, payload);
  }

  try {
    const response = await fetch(`${API_BASE}${endpoint}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      throw new Error('API request failed');
    }

    return await response.json();
  } catch (error) {
    console.warn('AI API not available, using stub response');
    return getStubResponse(endpoint, payload);
  }
}

function getStubResponse(endpoint: string, payload: Record<string, unknown>): AIResponse {
  const stubs: Record<string, string> = {
    '/api/ai/session-recap': `## Session Recap\n\n**Summary:** This session focused on ${payload.notes || 'various topics'}.\n\n**Key Points:**\n- Discussed project requirements\n- Reviewed timeline expectations\n- Established next steps\n\n**Action Items:**\n1. Follow up with client\n2. Prepare deliverables\n3. Schedule next session\n\n*Generated by AI (Demo Mode)*`,
    '/api/ai/take-log': `## Take Log\n\n| Time | Description | Notes |\n|------|-------------|-------|\n| 00:00 | Session start | Setup complete |\n| 05:00 | First take | Good energy |\n| 12:00 | Second take | Best version |\n| 18:00 | Final review | Approved |\n\n*Generated by AI (Demo Mode)*`,
    '/api/ai/follow-up': `Hey! 👋\n\nThank you for the session today. Here's a quick summary:\n\n✅ Session completed successfully\n📅 Next steps discussed\n💰 Invoice will be sent separately\n\nLooking forward to working together again!\n\n— Push-A-Yute Team\n\n*Generated by AI (Demo Mode)*`,
    '/api/ai/lead-summary': `## Lead Analysis\n\n**Lead Quality:** High\n**Recommended Action:** Priority follow-up\n\n**Key Insights:**\n- Budget aligns with talent tier\n- Event type matches artist expertise\n- Timeline is favorable\n\n*Generated by AI (Demo Mode)*`,
    '/api/ai/weekly-insights': `## Weekly Insights\n\n**Performance Highlights:**\n- 23% increase in booking requests\n- Top converting talent: DJ Phantom\n- Most requested category: DJ\n\n**Recommendations:**\n- Feature more Band acts on homepage\n- Follow up with 3 pending leads\n- Consider expanding to new markets\n\n*Generated by AI (Demo Mode)*`,
  };

  return {
    success: true,
    data: stubs[endpoint] || 'AI response placeholder (Demo Mode)',
  };
}

export const aiService = {
  generateSessionRecap: (notes: string) => 
    callAI('/api/ai/session-recap', { notes }),
  
  generateTakeLog: (notes: string) => 
    callAI('/api/ai/take-log', { notes }),
  
  generateFollowUp: (context: { clientName: string; eventType: string; messageType: string }) => 
    callAI('/api/ai/follow-up', context),
  
  generateLeadSummary: (lead: Record<string, unknown>) => 
    callAI('/api/ai/lead-summary', { lead }),
  
  generateWeeklyInsights: () => 
    callAI('/api/ai/weekly-insights', {}),
};
